"""Add user relationship

Revision ID: 006b3d2dcec7
Revises: 55c966620c1a
Create Date: 2025-03-09 02:38:57.509027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006b3d2dcec7'
down_revision = '55c966620c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gra_action_hub', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['ah_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gra_action_hub', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
