"""Update table name to gra_action_hub.

Revision ID: 55c966620c1a
Revises: 1d88d7ad1346
Create Date: 2025-03-09 02:12:02.489551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c966620c1a'
down_revision = '1d88d7ad1346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gra_action_hub',
    sa.Column('ah_id', sa.Integer(), nullable=False),
    sa.Column('ah_type', sa.String(length=50), nullable=False),
    sa.Column('ah_report_id', sa.Integer(), nullable=False),
    sa.Column('ah_user_id', sa.Integer(), nullable=False),
    sa.Column('ah_content', sa.Text(), nullable=True),
    sa.Column('ah_created_at', sa.DateTime(), nullable=False),
    sa.Column('ah_updated_at', sa.DateTime(), nullable=True),
    sa.Column('ah_status', sa.SmallInteger(), nullable=False),
    sa.Column('ah_parent_id', sa.Integer(), nullable=True),
    sa.Column('ah_mentioned_user_id', sa.Integer(), nullable=True),
    sa.Column('ah_is_read', sa.Boolean(), nullable=True),
    sa.Column('ah_section_id', sa.Integer(), nullable=True),
    sa.Column('ah_subsection_id', sa.Integer(), nullable=True),
    sa.Column('ah_last_read_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ah_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('gra_action_hub')
    # ### end Alembic commands ###
